- server/routes/games.js
- server/test/games.test.js
This is version 1 of the GET /api/games/battle endpoint. It returns an array containing two games. Each game has the following properties: id, name.
> Feature/games list - GET /api/games/battle V1

- server/routes/games.js
- server/test/games.test.js
GET /api/games/battle should now return two random games from the games array.
> Add randomness to GET /api/games/battle

- server/db/data.js
- server/models/game.js
- server/routes/games.js
- server/test/games.test.js
Adds the 'igdbId' property to the Game model. Doesn't serve any purpose right now, but it will become important when we want to add more games later. I also updated the GET /api/games/battle endpoint to remove the possibility of returning the same game for both spots in the array.
> Feature/games list - Add igdbId to Game model

- server/db/data.js
- server/models/game.js
- server/test/games.test.js
Adds the coverUrl prop to the Game model. coverUrl contains a string which should be the absolute URL to the cover image on the IGDB servers.
> Feature/games list - Add coverUrl to Game model

- .travis.yml
- server/db/data.js
- server/models/game.js
- server/test/games.test.js
Restructures IGDB information in the Game model into its own object with `id` and `slug` properties. Also updates the Travis config file to only run on the "master" and "dev" branches.
> Feature/games list - Add IGDB slug to Game model

- client/src/actions/gameActions.js
- client/src/components/card.js
- client/src/components/landing-page.js
This pull requests addresses the need to send ID's rather than game names to the server when a Vote is registered and dispatches the vote action, which sends data to the server
> dispatch handleVote sends id's now instead of game names

- server/db-mongoose.js
- server/db/data.js
- server/models/game.js
- server/package.json
- server/routes/games.js
- server/test/games.test.js
- server/utils/gameApi.js
Adding the POST /api/games endpoint. It takes in an IGDB ID and returns the new Game object in the database. It takes a long and convoluted route to get there, requiring two calls to the IGDB API via the apicalypse package. Let me know if you need me to explain anything along the journey.
> Feature/games list - POST /api/games

- client/src/actions/gameActions.js
- client/src/components/battle.js
- client/src/components/card.js
- client/src/components/landing-page.js
- client/src/components/styles/card.css
- client/src/components/styles/landing-page.css
- client/src/components/styles/vote-stats.css
- client/src/components/vote-card.js
- client/src/components/vote-stats.js
- client/src/reducers/gameReducer.js
- server/db/test-data.js
- server/models/game.js
- server/routes/games.js
- server/routes/history.js
- server/test/games.test.js
- server/utils/gameApi.js
- server/utils/queries.js
Refactors process to retrieve coverURL. Adds summary, genres, platforms, and similar_games to Game model and POST /api/games endpoint. Summary is a string. Genres, platforms, and similar_games are arrays. Each item in genres and platforms is an object with name and id properties. Each item in similar_games is a IGDB ID number.
> Features/game info - Update POST /api/games

- server/routes/games.js
- server/test/games.test.js
- server/test/history.test.js
Adds the ability to filter GET /api/games results using a 'slug' query.
> Features/slug search - Add slug filter to GET /api/games

- server/db/data.js
- server/package-lock.json
- server/routes/games.js
- server/test/.eslintrc
- server/test/auth.test.js
- server/test/games.test.js
Had to redo this PR because some middleware for the POST endpoint was taken out.
> Features/game info - Add PUT /api/games/:id

- server/routes/history.js
- server/utils/queries.js
- server/utils/scratch.js
This PR adds an endpoint to history that gives us all the games with the amount of times played, amount of times won and percentage won
> GET /history/all endpoint

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/actions/gameActions.js
- client/src/components/Game.js
- client/src/components/GameDetails.js
- client/src/components/GameInfo.js
- client/src/components/GameSimilar.js
- client/src/components/Games.js
- client/src/components/MenuItem.js
- client/src/components/app.js
- client/src/components/app.test.js
- client/src/components/header-bar.js
- client/src/reducers/allGamesReducer.js
- client/src/reducers/gameReducer.js
- client/src/setupTests.js
- server/db/test-data.js
- server/routes/games.js
Adds a refresh button to the game info page.
> Features/game info - Add refresh button to client

- server/.eslintrc.json
- server/db-mongoose.js
- server/db/data.js
- server/routes/history.js
- server/routes/users.js
- server/test/games.test.js
- server/test/history.test.js
- server/test/users.test.js
Adds the GET /api/games/:id/recommendations endpoint. This endpoint returns an array of no more than five games.  The recommendation algorithm finds the top 100 games a user has chosen, extracts all similar games from those top 100 games, counts the number of times each similar game is mentioned, and returns the five similar games listed most frequently.
> Feature/rec endpoint - Add GET /api/games/:id/recommendations endpoint

- client/src/components/Games.js
- fixed scrolling issue in non-Chrome/Firefox browsers
> merge with dev

- server/models/user.js
- server/test/users.test.js
- server/utils/queries.js
Add a numeric 'battles' property to the User model.
> Feature/battle filters - Add battles property to User model

- server/routes/history.js
- server/test/history.test.js
- server/utils/imagesApi.js
When a vote is recorded through the POST /api/history endpoint, the user's battles count is increased by one.
> Feature/battle filters - Update battles count on POST /api/history

- server/.eslintrc.json
- server/db/test-data.js
- server/models/game.js
- server/passport/jwt.js
- server/routes/games.js
- server/test/games.test.js
- server/utils/gameApi.js
- server/utils/imagesApi.js
Added the firstReleaseDate property to the Game model. Updated the POST /api/games and PUT /api/games/:id to pull "first_release_date" from IGDB and assign it to firstReleaseDate.
> Feature/battle filters - Add firstReleaseDate prop to Game model

- server/db-mongoose.js
- server/db/data.js
- server/index.js
- server/routes/games.js
- server/routes/validators.js
- server/test/games.test.js
- server/test/setup.test.js
- server/utils/gameApi.js
Restricts access to PUT /api/games/:id to admins.
> Feature/admin - Restrict PUT /api/games/:id to admins

- client/src/components/battle.js
- client/src/components/card.js
- client/src/components/card.test.js
- client/src/components/styles/card.css
Updates the battle screen styles to be more responsive and consistent.
> Polish/battle screen - Update battle screen styles

- client/src/actions/gameActions.js
- client/src/components/userOnboard.js
- client/src/components/userOnboard.test.js
- server/routes/games.js
Updates the fetchGames action to include an authToken if one exists. The GET /api/games/battle endpoint now will accept that authToken if it exists and grab the user's neverPlayed array. It uses that array to filter the list of games returned.
> Feature/never played - Filter GET /api/games/battle by neverPlayed

- client/src/components/Games.js
- client/src/components/Games.test.js
- client/src/components/ProfilePage.js
- client/src/components/RecommendationsPage.js
- client/src/components/WishList.js
I appear to have fixed the memory leak, though I'm not sure why. *shrug*
> Bug/memory leak - Fixed memory leak?

- client/src/actions/gameActions.js
- client/src/components/errorBoundary.test.js
- client/src/components/landing-page.js
- client/src/reducers/gameReducer.js
Fixes the issue where the onboarding process would briefly appear when loading the voting page.
> Fix loading issue on vote page

- client/src/actions/gameActions.js
- client/src/components/app.js
- client/src/components/landing-page.js
- client/src/components/styles/app.css
- client/src/components/styles/landing-page.css
Replaces the static loading message with the loading bar.
> Replace loading message with loading bar

- client/src/components/about.js
- client/src/components/footer.js
- client/src/components/header-bar.js
Moves the "About" link from the header to the footer and adds a link to the GitHub repo in the About page.
> Move About link to footer

- server/routes/users.js
- server/utils/recommendations.js
Fixed a bug in the recommendations page where if all boxes were unchecked, it would only pull in games that had 'PC' in the platforms...now it will pull all.
> fixed bug where leaving no checks would only pull PC games

- client/src/components/__test__/GameDetails.test.js
- client/src/components/__test__/Games.test.js
- client/src/components/__test__/RecommendationsPage.test.js
- client/src/components/__test__/WishListPage.test.js
- client/src/components/__test__/battle.test.js
- client/src/components/__test__/card.test.js
- client/src/components/__test__/landing-page.test.js
- client/src/components/__test__/login-form.test.js
- client/src/components/__test__/userOnboard.test.js
- client/src/components/gamePage/Game.js
- client/src/components/onBoard/login-form.js
- client/src/components/recommendations/WishListPage.js
The remove button now only shows up on wishlist games when the visitor is logged in and viewing their own wishlist.
> Bug/public wishlists - Fix remove button

- client/src/actions/users.js
- client/src/components/__test__/WishList.test.js
- client/src/components/app.js
- client/src/components/gamePage/Game.js
- client/src/components/profile/ProfilePage.js
- client/src/components/recommendations/RecommendationsList.js
- client/src/components/recommendations/WishList.js
- client/src/components/recommendations/WishListPage.js
- client/src/reducers/userReducer.js
- server/.eslintrc.json
- server/db/data.js
- server/db/test-data.js
- server/db/test-wishListRes.js
- server/models/user.js
- server/routes/games.js
- server/routes/users.js
- server/test/users.test.js
Updates the GET wishlist endpoint to retrieve games from the database first and only query the API for any games that were not located in the database. Plus lots of refactoring of the wishlist actions and the user endpoints.
> Bug/wishlist limit - Fix 10 item limit on wishlist

- client/src/components/onBoard/landing-page.js
- client/src/local-storage.js
Fixed an issue where a logged in user would get trapped on the "Just a moment..." screen when they reloaded the root URL.
> Bug/just a moment - Fix logged in root URL issue
